### ISSUE TITLE
Text changes the line while beeing written

### ISSUE THREAD

**Issue by jppresents** [netgfx/Phaser-typewriter#1]
I have only quickly watched the example, but it really stuck out, that the last word in a line flips to the next line if it is too long to fit in the old line.

With the (really nice) handwriting sound in the background, this effect totally breaks the illusion of something physically beein written.

If possible the plugin should never try to write a word into the line if it will not fit.

**Comment by netgfx** [comment]
Well that can be easily fixed by placing \n in the actual text or modifying the maxWidth value to accommodate and wrap the text on a space.
I'm using maxWidth value of Phaser BitmapText for this.

**Comment by ztiromoritz** [comment]
Another solution could be to render the whole text, set alpha of every letter to 0, and then reveal the text letter by letter. See my pull request for this solution. 
(https://github.com/netgfx/Phaser-typewriter/pull/2/files)
I already did sth. like this with html/jquery once.

**Comment by netgfx** [comment]
Very nice addition, thanks for the pull request, I already merged it in.

**Comment by halflings** [comment]
It would be a good idea to update the demo with this fix! I was also bothered with that line "jump", so it's good to know that it has been fixed!

**Comment by netgfx** [comment]
Done!

**Comment by halflings** [comment]
Awesome! :+1:
